"""
AgentFi — Market Signals Router
Exposes multi-agent market intelligence, onchain whale inflows, sentiment, and technical indicators.
"""
import uuid
from typing import Optional
from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import structlog
import time

from database import get_db
from models import MarketSignal, SignalType, RiskLevel, User
from services.auth_service import get_current_user
from packages.agents.agents import MultiAgentOrchestrator

logger = structlog.get_logger()
router = APIRouter()
orchestrator = MultiAgentOrchestrator()


@router.get("/")
async def list_signals(
    asset: Optional[str] = Query(None, description="Filter by asset symbol, e.g. ETH, BTC"),
    limit: int = Query(10, ge=1, le=50),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Retrieve the latest live market intelligence signals generated by the agent swarm."""
    # Query database signals first
    stmt = select(MarketSignal).order_by(MarketSignal.created_at.desc()).limit(limit)
    if asset:
        stmt = stmt.where(MarketSignal.asset == asset.upper())

    res = await db.execute(stmt)
    signals = res.scalars().all()

    if signals:
        return {
            "signals": [
                {
                    "id": str(s.id),
                    "agent_id": str(s.agent_id) if s.agent_id else None,
                    "asset": s.asset,
                    "signal_type": s.signal_type.value if hasattr(s.signal_type, "value") else str(s.signal_type),
                    "confidence": s.confidence,
                    "risk_level": s.risk_level.value if hasattr(s.risk_level, "value") else str(s.risk_level),
                    "evidence": s.evidence,
                    "created_at": s.created_at.isoformat() if s.created_at else None
                }
                for s in signals
            ]
        }

    # If database has no signals yet, run live multi-agent analysis dynamically
    target_asset = asset.upper() if asset else "ETH"
    live_alpha = await orchestrator.generate_alpha_recommendation(asset=target_asset)

    return {
        "signals": [
            {
                "id": f"sig_{target_asset.lower()}_alpha",
                "asset": target_asset,
                "signal_type": live_alpha.recommendation,
                "composite_score": live_alpha.composite_score,
                "confidence": live_alpha.confidence,
                "risk_level": live_alpha.risk_level,
                "evidence": live_alpha.explainability,
                "agent_breakdown": live_alpha.signals,
                "created_at": time.time()
            }
        ]
    }


@router.get("/{signal_id}")
async def get_signal(
    signal_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get single signal with full explainability trace."""
    try:
        sig_uuid = uuid.UUID(signal_id)
        stmt = select(MarketSignal).where(MarketSignal.id == sig_uuid)
        res = await db.execute(stmt)
        s = res.scalar_one_or_none()
        if s:
            return {
                "id": str(s.id),
                "asset": s.asset,
                "signal_type": s.signal_type.value if hasattr(s.signal_type, "value") else str(s.signal_type),
                "confidence": s.confidence,
                "risk_level": s.risk_level.value if hasattr(s.risk_level, "value") else str(s.risk_level),
                "evidence": s.evidence,
                "created_at": s.created_at.isoformat() if s.created_at else None
            }
    except ValueError:
        pass

    # Dynamic fallback
    alpha = await orchestrator.generate_alpha_recommendation(asset="ETH")
    return {
        "id": signal_id,
        "asset": "ETH",
        "composite_score": alpha.composite_score,
        "recommendation": alpha.recommendation,
        "explainability": alpha.explainability
    }
